apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: splunkforwarders.splunkforwarder.managed.openshift.io
spec:
  group: splunkforwarder.managed.openshift.io
  names:
    kind: SplunkForwarder
    listKind: SplunkForwarderList
    plural: splunkforwarders
    singular: splunkforwarder
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterID:
              type: string
            image:
              type: string
            imageTag:
              type: string
            splunkInputs:
              items:
                properties:
                  blackList:
                    type: string
                  index:
                    type: string
                  path:
                    type: string
                  sourceType:
                    type: string
                  whiteList:
                    type: string
                required:
                - path
                type: object
              type: array
            splunkLicenseAccepted:
              type: boolean
          required:
          - image
          - imageTag
          - splunkInputs
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
